// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAzWhL9UQNAYUz-CHwYg8afhM2wspVa10',
    appId: '1:327211200766:web:0d392b90523347deadb5af',
    messagingSenderId: '327211200766',
    projectId: 'spotify-5f9dd',
    authDomain: 'spotify-5f9dd.firebaseapp.com',
    storageBucket: 'spotify-5f9dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDM2QrQdWBNryT2VBFhai21vztVkxB9rY',
    appId: '1:327211200766:android:0d10ad9f0642324badb5af',
    messagingSenderId: '327211200766',
    projectId: 'spotify-5f9dd',
    storageBucket: 'spotify-5f9dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2EMjdZomSITmgRUkTLbrvadgZ10KHKYI',
    appId: '1:327211200766:ios:4fc832cbb3115f31adb5af',
    messagingSenderId: '327211200766',
    projectId: 'spotify-5f9dd',
    storageBucket: 'spotify-5f9dd.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2EMjdZomSITmgRUkTLbrvadgZ10KHKYI',
    appId: '1:327211200766:ios:4fc832cbb3115f31adb5af',
    messagingSenderId: '327211200766',
    projectId: 'spotify-5f9dd',
    storageBucket: 'spotify-5f9dd.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAzWhL9UQNAYUz-CHwYg8afhM2wspVa10',
    appId: '1:327211200766:web:1a81a364f95b089cadb5af',
    messagingSenderId: '327211200766',
    projectId: 'spotify-5f9dd',
    authDomain: 'spotify-5f9dd.firebaseapp.com',
    storageBucket: 'spotify-5f9dd.appspot.com',
  );
}
