// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnKyU1zJjXz8URuFys6VAOmLq5ftFDloM',
    appId: '1:1086168108607:web:e835d438a740131301f28a',
    messagingSenderId: '1086168108607',
    projectId: 'spotify1526',
    authDomain: 'spotify1526.firebaseapp.com',
    storageBucket: 'spotify1526.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfn13yW86iSRPvnIAzE_nPfzS5g_hPCyY',
    appId: '1:1086168108607:android:d82c44399b9a33a601f28a',
    messagingSenderId: '1086168108607',
    projectId: 'spotify1526',
    storageBucket: 'spotify1526.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaIC99aAdvHyEo4-SHcb05j3-P3pO8TBs',
    appId: '1:1086168108607:ios:50a92ee974237a2f01f28a',
    messagingSenderId: '1086168108607',
    projectId: 'spotify1526',
    storageBucket: 'spotify1526.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaIC99aAdvHyEo4-SHcb05j3-P3pO8TBs',
    appId: '1:1086168108607:ios:50a92ee974237a2f01f28a',
    messagingSenderId: '1086168108607',
    projectId: 'spotify1526',
    storageBucket: 'spotify1526.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnKyU1zJjXz8URuFys6VAOmLq5ftFDloM',
    appId: '1:1086168108607:web:ce46a2b49be50d8201f28a',
    messagingSenderId: '1086168108607',
    projectId: 'spotify1526',
    authDomain: 'spotify1526.firebaseapp.com',
    storageBucket: 'spotify1526.appspot.com',
  );
}
